# AcadGild_DataScience_Assignment_6

Problem Statement 1:
Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically,
when increasing is False, the i-th output column is the input vector raised element-wise
to the power of N - i - 1.

In [16]:
#Solution

# Import numpy module to access methodsn and fucntion for array/matrix
import numpy as num_py

# Function
def matrix_Vandermonde(input_vector,n,bool_arg):
    '''This function Will return Matrix in which 
    the columns of the output matrix are powers of the input vector.'''
    
    output_matrix=num_py.vander(x=input_vector,N=n,increasing=bool_arg)
    return output_matrix

# input paramater
input_vector = num_py.arange(5,13,2)   # input vector ( 1-D array)
n = 5                                  # no. of column in matrix 
bool_arg_T = True                      # boolean argument
bool_arg_F = False                     # boolean argument

# function execution
out_matrix_True=matrix_Vandermonde(input_vector,n,bool_arg_T)

out_matrix_False=matrix_Vandermonde(input_vector,n,bool_arg_F)

#output
print("Input vector \n",input_vector,"\n")
print("Output Matrix , when boolean argument is True: \n",out_matrix_True,"\n")
print("Output Matrix , when boolean argument is False: \n",out_matrix_False)

Input vector 
 [ 5  7  9 11] 

Output Matrix , when boolean argument is True: 
 [[    1     5    25   125   625]
 [    1     7    49   343  2401]
 [    1     9    81   729  6561]
 [    1    11   121  1331 14641]] 

Output Matrix , when boolean argument is False: 
 [[  625   125    25     5     1]
 [ 2401   343    49     7     1]
 [ 6561   729    81     9     1]
 [14641  1331   121    11     1]]
